In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("ambitionbox_companies.csv")

## How big is the data

In [3]:
df.shape

(980, 5)

## How does data look like?

In [4]:
df.head()

     Company  Rating Reviews Salaries   Jobs
0        TCS     3.3    1.2L    10.4L   5.1k
1  Accenture     3.7   76.2k     7.3L  14.8k
2      Wipro     3.6   67.1k     4.9L      3
3  Cognizant     3.7   63.4k     6.1L    915
4  Capgemini     3.6   55.6k       5L   2.1k

In [5]:
df.sample(5) #this will give random 5 value

                   Company  Rating Reviews Salaries Jobs
607        Clover Infotech     3.3    1.7k    12.4k  213
479    Huawei Technologies     4.1    2.1k     7.6k   34
336  Tata Advanced Systems     3.7    2.8k    13.5k   12
23     Kotak Mahindra Bank     3.6   23.3k    89.4k  205
154                  Bosch     4.1    4.8k    21.6k   --

## What is the data type of cols?

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 980 entries, 0 to 979
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Company   980 non-null    object
 1   Rating    980 non-null    float64
 2   Reviews   980 non-null    object
 3   Salaries  980 non-null    object
 4   Jobs      980 non-null    object
dtypes: float64(1), object(4)
memory usage: 38.4+ KB

## Are there is any missing  values?

In [7]:
df.isnull().sum()

Company     0
Rating      0
Reviews     0
Salaries    0
Jobs        0
dtype: int64

## How does the data look mathematically?

In [8]:
df.describe()

           Rating
count  980.000000
mean     3.785000
std      0.335855
min      1.300000
25%      3.600000
50%      3.800000
75%      4.000000
max      4.900000

## Are there duplicate values?

In [9]:
df.duplicated().sum()

np.int64(0)

## how is the correlation between the cols?

In [10]:
df.corr(numeric_only=True)

        Rating
Rating     1.0