In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('cars.csv')

In [3]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

# One Hot Encoding using pandas '

In [8]:
pd.get_dummies(df,columns=['fuel','owner'],dtype=int, drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,1,0,0,0,0,0,0
1,Skoda,120000,370000,1,0,0,0,1,0,0
2,Honda,140000,158000,0,0,1,0,0,0,1
3,Hyundai,127000,225000,1,0,0,0,0,0,0
4,Maruti,120000,130000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,1,0,0,0,0
8124,Hyundai,119000,135000,1,0,0,1,0,0,0
8125,Maruti,120000,382000,1,0,0,0,0,0,0
8126,Tata,25000,290000,1,0,0,0,0,0,0
8127,Tata,25000,290000,1,0,0,0,0,0,0

# **Problem of doing One Hot Encoding using pandas**
is that Pandas does't remember which col. pandas give which position

# One Hot Encoding using Sklearn

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=2)

In [11]:
from sklearn.preprocessing import OneHotEncoder

In [14]:
ohe = OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)
# sparese false will convery data into array

In [15]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])

In [16]:
X_test_new = ohe.transform(X_test[['fuel','owner']])

In [18]:
X_train.shape

(6502, 4)

In [19]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Hyundai', 35000, 1, ..., 0, 0, 0],
       ['Jeep', 60000, 1, ..., 0, 0, 0],
       ['Hyundai', 25000, 0, ..., 0, 0, 0],
       ...,
       ['Tata', 15000, 0, ..., 0, 0, 0],
       ['Maruti', 32500, 1, ..., 1, 0, 0],
       ['Isuzu', 121000, 1, ..., 0, 0, 0]], dtype=object)

# for Categorical data in which large cateogry are presenet like car brand
in this we define thrashold those car brand which have more then 100 cars then we define sepereate col otherwise there is uncommon cols is define for car which have less then 100 cars

In [21]:
counts = df['brand'].value_counts()

In [22]:
df['brand'].unique()
thrashold = 100

In [23]:
rpl = counts[counts <= thrashold].index

In [30]:
pd.get_dummies(df['brand'].replace(rpl, 'uncommon'), dtype=np.int32).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
1627,0,0,0,0,1,0,0,0,0,0,0,0,0
3814,0,0,0,0,0,0,0,0,0,0,1,0,0
6386,0,0,0,0,0,0,1,0,0,0,0,0,0
3067,0,0,1,0,0,0,0,0,0,0,0,0,0
8125,0,0,0,0,0,0,1,0,0,0,0,0,0